// GENERATED by optiq/scripts/build-horizon-assets.mjs — do not edit by hand.
// Dimensions and LQIP placeholders for the Horizon '26 brand assets in /public/horizon.

export type HorizonAsset = {
  src: string;
  /** 1200w JPEG for Open Graph / Twitter cards — crawlers don't decode webp. */
  og: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const HORIZON: Record<"horizon-banner" | "horizon-july-30" | "amaka-horizon" | "optiq-horizon" | "davelabs-silvery" | "dave-keynote" | "dave-portrait", HorizonAsset> = {
  "horizon-banner": {
    "src": "/horizon/horizon-banner.webp",
    "og": "/horizon/horizon-banner.jpg",
    "width": 2048,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJbACdGuAAiiJ5RJAAP3i3+HtGt8aGRzlEbJYaUxeOqYBYACO3ZN8VNBFLg3FLKKtSUev0Kw3UQsCZ1B6iQAA"
  },
  "horizon-july-30": {
    "src": "/horizon/horizon-july-30.webp",
    "og": "/horizon/horizon-july-30.jpg",
    "width": 2048,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJYwAAt0NedrlkAAA/vUjJ5u77anG1bhmbB5JY1k7UoOhA4pdSE2G+OoOPnsWmhKX2eiPAAAFRBbMynt58AAA"
  },
  "amaka-horizon": {
    "src": "/horizon/amaka-horizon.webp",
    "og": "/horizon/amaka-horizon.jpg",
    "width": 2048,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJYwAAtiPbVpwAP7yO/lk+ExN3lhf6h6kHyTifoD76m2/vtuB0JXHa1gctgcRk8qg9SiE/dm8eUKFiIgAAA=="
  },
  "optiq-horizon": {
    "src": "/horizon/optiq-horizon.webp",
    "og": "/horizon/optiq-horizon.jpg",
    "width": 2048,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJZQAAu0e25DQAP71Iyebu+2pxtYYfIu9khEVHcS+fv2D50pQU6PjpctQ0aKIe/uKUAAAabgffCYlsAAAAA=="
  },
  "davelabs-silvery": {
    "src": "/horizon/davelabs-silvery.webp",
    "og": "/horizon/davelabs-silvery.jpg",
    "width": 2048,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkAA4BaJaQAAqo7jq2AAP75yOU5L6hQkxA1n5ZQpOcnOjEuqHcuExhhgAAA"
  },
  "dave-keynote": {
    "src": "/horizon/dave-keynote.webp",
    "og": "/horizon/dave-keynote.jpg",
    "width": 2048,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAA4BaJYwCw7E1XxtX4wdQAP6iRxYg37lHTwEG2H2w3i+mdubgWH6ZXmfW00b56sWvVP28bslTnKWk3r4RzVsMTv0AAAA="
  },
  "dave-portrait": {
    "src": "/horizon/dave-portrait.webp",
    "og": "/horizon/dave-portrait.jpg",
    "width": 2032,
    "height": 1143,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAkAA4BaJZgCdAEYEi6XbleAAP7dgPiz1lHZzPBK4wMg7EEu2+80m6KStdohvhVY7K0OeILMvy627JrY4uE7OW2T3y4I5sAAAA=="
  }
};
